Repository redhat-appstudio/tssc-sample-pipelines, pull requests merged in 2024-07, with the labels that each got.

#44 Update tuf and rekor urls for rhtap 1.2
  pac/pipelines/gitops-pull-request-rhtap.yaml
Labels: lgtm, ok-to-test

#47 gitops-repo: don't fail if TPA isn't configured
  pac/gitops-repo/gitops-on-pull-request.yaml
Labels: lgtm, approved

#48 fix: Update ec-tuf-mirror url for RHTAP 1.2
  pac/pipelines/gitops-pull-request-rhtap.yaml
Labels: lgtm
